{% set version = "2.2.0" %}

package:
  name: horton 
  version: {{ version }}

source:
  path: ..

build:
  number: 1
  binary_relocation: true

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ compiler("fortran") }}
    - cmake
    - make
    - git
    - python {{ python }}
  host:
    - numpy
    - scipy
    - cython
    - h5py
    - matplotlib
    - libxc
    - libint
  run:
    - python
    - numpy
    - scipy
    - h5py
    - matplotlib
    - libxc
    - libint
    - cython
test:
  imports:
    - horton

about:
  summary: "Helpful Open-source Research TOol for N-fermion systems"
  license: GPLv3.0
  home: https://github.com/theochem/horton
