{% set version = "2.2.0" %}

package:
  name: horton 
  version: {{ version }}

source:
  path: ..

build:
  number: 1
  binary_relocation: true

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ compiler("fortran") }}
    - cmake
    - make
    - git
  host:
    - python
    - numpy
    - scipy
    - cython
    - h5py
    - matplotlib
    - libxc
    - libint
  run:
    - python
    - numpy
    - scipy
    - h5py
    - matplotlib
    - libxc
    - libint
    - cython
test:
  imports:
    - horton

about:
  summary: "Python-based Simulations of Chemistry Framework"
  license: Apache License 2.0
  home: http://www.pyscf.org
